### ISSUE TITLE
Unable to rebind symbols exported from a module in Chicken

### ISSUE THREAD

**Issue by ane** [jaor/geiser#114]
Let's say I have loaded a module with `,l module.scm` which exports some procedure `foo`. If I go to the definition of the procedure and try to eval it with <kbd>C-M-x</kbd>, nothing happens.

I mentioned this to the chicken geiser dude, and he said this is a known bug in Chicken.

**Comment by dleslie** [comment]
Yep, you came to the right place.

I brought this up with the Chicken hackers a few days ago and they were incredulous. I retested with Chicken 4.10.1, the current dev snapshot, and it worked.

So, erm, it seems that it may be fixed in the forthcoming 4.11.0 release of Chicken.

Specifically, I tested the following:

```scheme
(module foo * (import scheme) (define a 1))
(import foo)
a
(module foo * (import scheme) (define a 2))
(import foo)
a
```

Which worked as expected. Then I tested simply evaluating the ``(define a 2)`` from within Emacs, with the above code. And it worked as expected.

Ie, the buffer was:

```scheme
(module foo *
   (define a 1))
```

* Pressed ``C-c C-b`` to eval the buffer
* Eval'd ``(import foo)`` in the REPL
* Changed ``(define a 1)`` to ``(define a 22)``
* Pressed ``C-M-x`` at the correct point
* Eval'd ``a`` in the REPL and it was 22

**Comment by dleslie** [comment]
So... What version of Chicken are you using?

It seems to me that there is still a bug with the latest: when you eval a definition the result should show in the message area.

**Comment by ane** [comment]
I actually downgraded chicken to 4.9.0.1 to see if that version worked. I had 4.10.1 previously but it would just start freezing Emacs after a while if I tried to re-eval it. 

So in the new version it actually *did* do something, but it would begin freezing Emacs. The old version of 4.9.0.1 does nothing. I was using **4.10.0** before that.

Also if I'm editing a top-level module nothing seems to happen if I try to eval it with either geiser-eval-definition or -buffer,

I'll try with 4.10.1 tomorrow.

**Comment by ane** [comment]
I mean, it would start freezing when evaling exported symbols after a while. I had done something like this

1. `,l module.scm`
2, `(import foo)`
3. `,m foo`
4. try to eval, the first few attempts worked but then freezing.

**Comment by dleslie** [comment]
Oh, that's interesting.

I found some freezing bugs that I think may be related to recent changes to the apropos egg and its ability to handle symbols; but I hadn't heard of this.

**Comment by dleslie** [comment]
Does the freezing kick in at about the time that eldoc should show something, or that auto-complete or company would show something?

'Cause I may have a fix soon. :smile:

**Comment by ane** [comment]
Yes, actually I had noticed some weird stuff with company and eldoc. I
actually had to disable automatic completion in company because it was
slow. This may be related, but it definitely occurs when I eval stuff, and
the eldoc isn't triggering anymore.

That said, I definitely can confirm those bugs related to eldoc and
company.

**Comment by dleslie** [comment]
Gathering completion results is slow with chicken when you have an environment of any reasonable size. The dominating call is to ``apropos``, and there's not much I can do at this point to improve it, if I continue to use that egg.

I think I'll make an issue for 0.9 to replace usage of apropos with some customized functionality; but only if that proves to be faster.

Otherwise, there are hangs in eldoc and company that I am presently addressing.

**Comment by ane** [comment]
Ok I tried with 4.10.1 and the latest geiser from MELPA.

I made a file called `test.scm` with the following content:

```scheme
(module foo * (import scheme) (define a 1))
```

When I evaluate that, nothing happens. So I went and debugged the elisp code. Debugging `geiser-debug--send-region` in `geiser-debug.el:188` and upon reaching the form `(geiser-eval--send/wait code)`, it produces this:

`Result: ((error (key . retort-syntax)) (output . "\nError: unbound variable: foo\n\n	Call history:\n\n	<syntax>	  (geiser-eval foo (quote (begin (module foo * (import scheme) (define a 1)))))\n	<syntax>	  (quote (begin (module foo * (import scheme) (define a 1))))\n	<syntax>	  (##core#quote (begin (module foo * (import scheme) (define a 1))))\n	<eval>	  (geiser-eval foo (quote (begin (module foo * (import scheme) (define a 1)))))	<--\n#;8> "))`

I went to the REPL, `,m geiser` and pasted this: `(geiser-eval foo (quote (begin (module foo * (import scheme) (define a 1)))))`. Says, unsurprisingly that `Error: unbound variable: geiser#foo`. Switching it to

```scheme
(geiser-eval 'foo (quote (begin (module foo * (import scheme) (define a 1)))))
```

Works. If I do it again, I run into the Chicken limitation of module redefinition. But going back to the buffer still produces the same error, so I can't change the definition of a (i.e. making it 2 and then `C-M-x`), which I could do by issuing `(geiser-eval 'foo (quote (define a 2)))` in the REPL. That gives a warning, but it *does* change `a`.

Weeeeird. So maybe there's a bug in Geiser? The module name doesn't get quoted or something.

**Comment by dleslie** [comment]
It breaks on Error: prompts, stupidly. This will be part of a forthcoming fix.Otherwise, that's odd. '''foo''' should be a symbol, not a variant. Huh.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Antoine KalmbachSent: Saturday, December 5, 2015 3:56 AMTo: jaor/geiserReply To: jaor/geiserCc: Dan LeslieSubject: Re: [geiser] Unable to rebind symbols exported from a module in Chicken (#114)Ok I tried with 4.10.1 and the latest geiser from MELPA.

I made a file called test.scm with the following content:

(module foo * (import scheme) (define a 1))

When I evaluate that, nothing happens. So I went and debugged the elisp code. Debugging geiser-debug--send-region in geiser-debug.el:188 and upon reaching the form (geiser-eval--send/wait code), it produces this:

Result: ((error (key . retort-syntax)) (output . "\nError: unbound variable: foo\n\n   Call history:\n\n   <syntax>      (geiser-eval foo (quote (begin (module foo * (import scheme) (define a 1)))))\n   <syntax>      (quote (begin (module foo * (import scheme) (define a 1))))\n <syntax>      (##core#quote (begin (module foo * (import scheme) (define a 1))))\n  <eval>    (geiser-eval foo (quote (begin (module foo * (import scheme) (define a 1))))) <--\n#;8> "))

I went to the REPL, ,m geiser and pasted this: (geiser-eval foo (quote (begin (module foo * (import scheme) (define a 1))))). Says, unsurprisingly that Error: unbound variable: geiser#foo. Switching it to

(geiser-eval 'foo (quote (begin (module foo * (import scheme) (define a 1)))))

Works. If I do it again, I run into the Chicken limitation of module redefinition. But going back to the buffer still produces the same error, so I can't change the definition of a (i.e. making it 2 and then C-M-x), which I could do by issuing (geiser-eval 'foo (quote (define a 2))) in the REPL. That gives a warning, but it does change a.

Weeeeird. So maybe there's a bug in Geiser? The module name doesn't get quoted or something.

—Reply to this email directly or view it on GitHub.

**Comment by ane** [comment]
I made a repo with some sample files to show what happens. The reproduction steps are in the README.

http://github.com/ane/geiser-break

**Comment by dleslie** [comment]
I have a fix for the Error above. It will be in with my next PR.

Chicken Errors will also be properly recognized by Geiser. It was a matter of 'error' vs 'Error'. :wink:

**Comment by dleslie** [comment]
Getting there...

Your test is interesting. The includes to files in the same directory break it, which shouldn't happen.

**Comment by dleslie** [comment]
BTW, thanks for all of the excellent testing.

**Comment by dleslie** [comment]
Getting there...

```scheme
=> #<unspecified>


; including bar.scm ...

Expression evaluated was:


;; -*- geiser-scheme-implementation: 'chicken -*-

(module foo (frobnicate)

(import chicken scheme)
(include "bar.scm")

)
```

**Comment by dleslie** [comment]
Completions work.

**Comment by dleslie** [comment]
There's some weird behaviour, but it's a Chicken thing.

In short: your ``bar.scm`` has no indication of the module in which the method resides, and so it is evaluated at top level when you evaluate the buffer. But, if you've already loaded and imported the module ``foo`` then ``frobnicate`` is exported. Rebinding ``frobnicate`` works as expected, despite the absence of module information. And yes, I tested both ``frobnicate`` and ``foo#frobnicate``.

Here be dragons.

**Comment by dleslie** [comment]
PR made.

#115

**Comment by ane** [comment]
Great :+1: 

Yeah I understand what happens when I rebind... let's just say that once module reloading works, I won't have to shim modules (i.e. include content to the module file with `include`) any more like this.

**Comment by ane** [comment]
It works a lot better now after upgrading to the newest version with the PR merged.

It still sometimes hangs for a while when re-evaluating a module though, even on 4.10.1.

**Comment by dleslie** [comment]
Antoine Kalmbach <notifications@github.com> writes:

> It works a lot better now after upgrading to the newest version with the PR merged.

Great news!


> It still sometimes hangs for a while when re-evaluating a module though, even on 4.10.1.

Damn.

You've been incredibly helpful thus far; but may I impose on you for
additional details? IE, is it the same example as before that causes
issues?

Moreover, supplying me with the contents of the Geiser debug buffer is
helpful; as is generating a Chicken debug log. The latter can be done by
retrieving the log file generated after entering the following in a
Chicken repl:

```scheme
(geiser-use-debug-log #t)
```

Thanks. :)

**Comment by ane** [comment]
The problem with the hanging is that it's now, after the PR, only intermittent. There is always the chance that it's related to my Emacs config. I'll have to investigate. There's no pattern. :horse: 

I can't even pin it down if it's reloading a module or just something that causes it.

**Comment by dleslie** [comment]
Guess I'll have to keep looking.
:mag:

**Comment by ane** [comment]
Haven't been able to crash it recently. I'll reopen if it reappears and I can pin it down.

**Comment by dleslie** [comment]
Thanks!
