### ISSUE TITLE
comint-next-prompt and comint-previous-prompt are faulty

### ISSUE THREAD

**Issue by fice-t** [jaor/geiser#162]
* Guile
`comint-previous-prompt` generally works fine, but `comint-next-prompt` goes to the start of the result line before going to a prompt.

* MIT
Neither work (they go to the whitespace lines above and below the `;Value:` line before going to a prompt).

Also, in Chicken/Guile if an error is displayed then both commands stop at one of the error lines before going to a prompt. The MIT behaviour stays the same (probably since it's the same basic format as the `;Value:` output).

I haven't tested the other Schemes out so far.

**Comment by jaor** [comment]
When using comint prompt regexps, comint's versions of these commands seem to not work well out of the box.  They use forward-paragraph, and as you've observed, the results are mixed.  Instead of trying to fight paragraph functions, in 2ca38a5, i've just defined `geiser-repl-{previous,next}-prompt` in a very naive way, and bound them to the usual `C-c C-p/n` in geiser repl buffers.  They work much better for me, but perhaps i'm missing corner cases: how do they work for you?

In case they're good enough (or when they're good enough), we could add around advice to comint's functions so that they call geiser's version in geiser-repl buffers, but i am not sure that's worth the trouble: what do you think, @fice-t?

**Comment by fice-t** [comment]
From that commit I got the warning: ``Warning: `previous-line' is for interactive use only``

I think it should use `(end-of-line 0)` rather than both `previous-line` and `end-of-line`.

Otherwise it seems to work in all the cases I've tried so far, thanks!

Though is there a specific reason why Geiser uses regexp prompts rather than relying on fields? I don't know much about comint myself, but all the other comint-based modes I've used seem to not use regexps. For example, fields might have not caused #21.

**Comment by jaor** [comment]
prompt regexps are (ugly as it sounds) part of the communication
protocol between the scheme process and emacs (they play the role of
end-of-message marker), and that is used by the task queue package
module tq to handle message passing.  but, before using tq, i was using
the comint-redirect family of functions, and those ones don't know how
to use fields.

so regexp prompts are there for historical reasons, but a naive attempt
to simply deactivate them (first thing i did when i saw this report)
didn't work: i'm relying on them somewhere else, and have to find out
where exactly before relying on fields.

(also, 620f0d0)

**Comment by fice-t** [comment]
Ah, that's unfortunate, but it makes sense.

Thanks for the fix.
