### ISSUE TITLE
C-c C-k only works if the file has been modified

### ISSUE THREAD

**Issue by raxod502** [jaor/geiser#187]
To reproduce:

```
emacs -Q
(load-file "~/.emacs.d/elpa/geiser-20161001.1854/geiser.el")
C-x C-f test.rkt RET
M-x run-geiser RET racket RET
```

The file `test.rkt` contains:

```
#lang racket

(displayln "Hello!")
```

When I press `C-c C-k`, `*Geiser dbg*` pops up with the text `Hello!`, as expected. But when I press `C-c C-k` again, the `Hello!` disappears! I still get the `Compiling /path/to/test.rkt ... done`, but the file is not actually evaluated.

If I modify the file with `M-! touch test.rkt RET`, then `C-c C-k` is returned to its original functionality. But only the first time; the second time, evaluation will once again not happen.

Am I misunderstanding something here? I expect the file to be evaluated every time I compile it. Perhaps this is an optimization by Racket where the file is not actually re-compiled if it's not been changed because it's supposed to be referentially transparent or something?

I ran into this problem using `rackunit`, since I will have a `my-functions.rkt` and a `my-functions-test.rkt`. I start out by compiling `my-functions-test.rkt` to see that my tests are failing, I fix up `my-functions.rkt`, and then re-compile `my-functions-test.rkt` (no need to change the latter file; my tests are already written). But since `my-functions-test.rkt` is not evaluated, it looks like my tests are succeeding even if they aren't, which is very confusing!

**Comment by raxod502** [comment]
I see code that looks like it's checking timestamps before going ahead with the compilation in `enter.rkt`:

```
(define (check-latest mod)
  (define mpi (module-path-index-join mod #f))
  (define done (make-hash))
  (let loop ([mpi mpi])
    (define rindex (module-path-index-resolve mpi))
    (define rpath (resolved-module-path-name rindex))
    (define path (if (pair? rpath) (car rpath) rpath))
    (when (path? path)
      (define npath (normal-case-path path))
      (unless (hash-ref done npath #f)
        (hash-set! done npath #t)
        (define mod (hash-ref loaded rpath #f))
        (when mod
          (for-each loop (mod-depends mod))
          (define-values (ts actual-path) (get-timestamp npath))
          (when (> ts (mod-timestamp mod))
            (define orig (current-load/use-compiled))
            (parameterize ([current-load/use-compiled
                            (make-loader orig #f)]
                           [current-module-declare-name rindex]
                           [current-module-declare-source actual-path])
              ((make-loader orig #f) npath (mod-name mod)))))))))
```

That would be consistent with the observed behavior. If it's intended, I am curious what the reason is.

**Comment by jaor** [comment]
That's intended behaviour, and actually the standard way racket modules
work: side effects are computed only once, when the module is first
loaded (the code you quoted is similar to what you can find in racket's
own `enter` implementation), and code is not reloaded if the file hasn't
been modified.

The deeper reasons for this behaviour are to be found in the
documentation for racket module system. in DrRacket things work just
fine everytime you "Run" the file (with the green button) because the
REPL is actually restarted everytime too.

Racket designers are very keen on that behaviour, and consider a bad
practice to maintain a live process that incrementally changes its state
to accommodate new (re)definitions.  They even have a motto for it: [the
top level is hopeless!](https://gist.github.com/samth/3083053) (just
follow the link for lots of links to further discussion).

Another area where this opposed world views will hit you is in
submodules: i have no clear model in my mind of how submodules are
supposed to work when code is re-evaluated in a living repl, and haven't
been able to implement their reloading in a way that makes intuitive
sense to me.  This is surely my fault, although i suspect that
submodules are designed with DrRacket's evaluation model in mind and
that it's difficult to adapt their behaviour to our modus operandi.

Probably, we would need someone with a better grasp of Racket to really
implement module and submodule reloading in a living REPL such as
geiser's in a way that makes full sense in Racket.  But my impression is
that racketeers by and large are not interested in geiser's way, and are
very happy with DrRacket (and racket-mode if they happen to use emacs),
so i'm not holding my breath :) i of course would love to be proved
wrong!

**Comment by raxod502** [comment]
Hmm. I am trying to be open to other programming paradigms, so I am wary of my inclination to make Racket just like CIDER. How does `racket-mode` compare to Geiser?

Also, how should I do TDD using `rackunit`, if one can't reload a file? Is there a Geiser command equivalent to the DrRacket "Run" button?

**Comment by jaor** [comment]
i haven't tried it myself, but i have the highest regard for greg,
racket-mode's author, and i'd definitely give it a try if you want to
stick to racket's paradigm (we've even considered droping support in
geiser for racket altogether in favour of racket-mode).

in geiser, you can run `M-x geiser-restart-repl` to, well, restart the repl,
and write a simple function that combines C-c C-k and restart-repl, but
perhaps it's easier to just "touch" the file:

```elisp
(defun touch-and-compile ()
  (interactive)
  (set-buffer-modified-p t)
  (save-buffer 0)
  (geiser-compile-current-buffer))
```
