### ISSUE TITLE
Invoke Geiser with plt-r5rs rather than Racket?

### ISSUE THREAD

**Issue by haziz** [jaor/geiser#198]
When using Geiser and Emacs for Scheme programming, how do I set Geiser to invoke plt-r5rs legacy scheme, or possibly the R6RS variant, instead of Racket in "racket" mode?

I want Racket, to function in R5RS (or possibly R6RS) mode within the REPL rather than in racket mode, which is deviating more and more from "standard" scheme.

**Comment by jaor** [comment]
sorry for the late response... no, invoking plt-r5rs is not going to
work because geiser asks the racket process using reflection apis that
are not available when it is started as plt-5rs.  what might work is
using #lang r5rs (instead of #lang racket) in your modules: i've tried a
bit and basic things look fine, but you might find problems.

**Comment by ylluminarious** [comment]
@haziz FYI, I've answered your same question [here](http://stackoverflow.com/q/41163134/2636454).

**Comment by jaor** [comment]
thanks for your feedback, @ylluminarious . marking this issue as closed (but feel free to reopen if any other clarification needed).

**Comment by ylluminarious** [comment]
@jaor Fine with me 👍

**Comment by ylluminarious** [comment]
@haziz FYI, I had to deal with this issue myself recently and I updated [my answer](http://stackoverflow.com/a/41842624/2636454) on SO to be better than before and you might find it acceptable now.
