### ISSUE TITLE
Geiser REPL only working with Guile and not other schemes  in Emacs. 

### ISSUE THREAD

**Issue by sdban** [jaor/geiser#200]
I have Geiser installed in emacs.  
When I open a scheme program  and run <code> C-c C-a </code> it starts a <code> guile </code> REPL that works as it should. 

Now when I try  <code> run-geiser</code> and select     racket  I get a REPL but cannot seem to use the functions in the original module. 

- I have interactively tried to change <code> geiser-active-implementation</code>  by changing order of scheme interpreters but that doesn't seem to work.   

Will be happy to provide more information.

**Comment by jaor** [comment]
this is by design: your original module is attached to the Guile REPL,
not to the Racket one.  definitions are not interchangeable (the schemes
we support are different, and there's no good way a new scheme process can
load the scheme code that it was loaded in the other).

if you want to choose the original buffer to another scheme, use
`geiser-set-scheme`, bound to `C-c C-s` in scheme buffers.

to modify the scheme implementation that is associated with a file by
default, please take a look at
http://geiser.nongnu.org/geiser_4.html#The-source-and-the-REPL

**Comment by sdban** [comment]
Thank you for the clarification. This solves it!
