### ISSUE TITLE
Understanding the term "current namespace"

### ISSUE THREAD

**Issue by sunqingyao** [jaor/geiser#206]
In [Modus operandi](http://www.nongnu.org/geiser/geiser_1.html#Modus-operandi), you said that(emphasis mine):

> Thus, all evaluations performed by Geiser either in the REPL or in a source code buffer happen in the context of **the current namespace**. Every time you switch to a different file, you’re switching namespaces automatically; at the REPL, you must request the switch explicitly (usually just using means provided by the Scheme implementation itself).

I cannot understand the bolded phrase "**the current namespace**" very well. Are you implying that there exists a "current namespace", which is common to a file and a REPL, where all evaluations performed by Geiser either in that REPL or in that source code buffer happen in?

In my understanding, each file has its exclusive namespace, and each REPL has its exclusive namespace, too. This believing is confirmed by the following part of [To eval or not to eval](http://www.nongnu.org/geiser/geiser_4.html#To-eval-or-not-to-eval):

> At the risk of repeating myself, i’ll remind you that all these evaluations will take place in the namespace of the module corresponding to the Scheme file from which you’re sending your code, which, in general, will be different from the REPL’s current module.

Could you please elaborate on this point a little more?

**Comment by raxod502** [comment]
The following is how it works in Clojure; I think the situation is more or less the same in Scheme(s).

The REPL has a current namespace, and that is the namespace in which symbols are resolved when they are not qualified with a namespace. Each file defines its own namespace, so the REPL's current namespace is the namespace for a file (or it could be one that you created just in the REPL). When you evaluate code from a file, it's evaluated in the namespace of the file. That is, if you evaluate `(def x 5)` from the file defining the namespace `my-namespace`, then the symbol `my-namespace/x` is defined, even if the REPL is currently in the namespace `other-namespace`. (Then you could refer to it as `namespace/x` in the REPL, or just `x` if you switched to namespace `my-namespace` in the REPL.)

I believe in Geiser, evaluating a file automatically switches the REPL to that namespace, because Scheme generally encourages a stronger association between the REPL and the file, discouraging long REPL sessions that gradually accumulate state (unlike Clojure).

The current namespace for the REPL is, of course, the namespace displayed in the REPL prompt (at least in Racket).

Hope this helps.

**Comment by jaor** [comment]
Thanks a lot for your very clear explanation, Radon.  Just a
clarification below (the rest is right):

> I believe in Geiser, evaluating a file automatically switches the REPL
> to that namespace, 

No, it doesn't.  It only switches the REPL if one evaluates the file
using a prefix argument (`C-u C-c C-k` instead of just `C-c C-k`, just
like Clojure's CIDER).

**Comment by sunqingyao** [comment]
Thank everyone for their responding. However, I'm just too dull to understand the following statements:

> Each file defines its own namespace, so the REPL's current namespace is the namespace for a file (or it could be one that you created just in the REPL). When you evaluate code from a file, it's evaluated in the namespace of the file.

Maybe an example can make the clarification easier: say, after starting a REPL, I open a file named `test1.scm`, which only contains a single variable definition:

    (define the-answer 42)

and I evaluate this definition with `C-c C-c`. Next, I switch to the REPL window, and evaluate `the-answer`. Unsurprisingly, the REPL prints `;Value: 42`.

Then, I switch back to the file buffer, close `test1.scm` with `<SPC> b d`, and open another file called `test2.scm`. Here is the content of `test2.scm`:

    (define double-answer (+ the-answer the-answer))

Now, evaluating `double-answer` gives me  `;Value: 84`.

The variable `the-answer` isn't defined in `test2.scm`, but no error has occurred. Doesn't this suggest that the variable definition in `test2.scm` is evaluated in the namespace of `test1.scm`? In this case, what does *current namespace* refer to? That of `test1.scm` or that of `test2.scm`?

**Comment by raxod502** [comment]
This behavior surprises me coming from a Clojure background. I think someone who knows more about Scheme will need to answer your question.

**Comment by jaor** [comment]
sunqingyao, in schemes like racket, each file has its own namespace by
default. in schemes like guile, you define the namespace of the current
file by a `(define-module ...)` declaration at the top.  in schemes like
MIT, there are no namespaces: all definitions go to a global one.

so, the discussion in previous messages refers to schemes like racket or
guile where you can define the namespace of a file.  in schemes like
MIT, or in guile if you don't use `define-module`, there is a
single. global namespace, shared by all files and the REPL, and all
evaluations go to that single namesapce.  that explains what your are
seeing.

**Comment by sunqingyao** [comment]
Great answer! I've understand it now.
