### ISSUE TITLE
Man page lookup from racket on OSX?

### ISSUE THREAD

**Issue by eatobin** [jaor/geiser#212]
I receive the the following error under OSX:

    Welcome to Racket v6.9.
    > (help and)
    Loading help index...
    Sending to web browser...
      file: /Applications/Racket v6.9/doc/reference/if.html
      anchor: (form._((lib._racket/private/letstx-scheme..rkt)._and))
    0:132: execution error: "file:///Applications/Racket%20v6.9/doc/reference/if.html#
    (form._((lib._racket%2Fprivate%2Fletstx-scheme..rkt)._and))" doesn’t understand the “open 
    location” message. (-1708)
    ; browser-run: process execute failed: '(#<path:/usr/bin/osascript> "-e" "open
    ;   location
    ;   \"file:///Applications/Racket%20v6.9/doc/reference/if.html#
    (form._((lib._racket%2Fprivate%2Fletstx-scheme..rkt)._and))\"")
    ;   [,bt for context]

Also happens with DrRacket.

Is this related to Issue #181?

Thank you!

**Comment by eatobin** [comment]
PS - Works as expected on my Linux machine:

    eric@linux-epth:~$ racket
    Welcome to Racket v6.9.
    > (help and)
    Loading help index...
    Sending to web browser...
      file: /home/eric/bin/racket/doc/reference/if.html
      anchor: (form._((lib._racket/private/letstx-scheme..rkt)._and))
    > 

Thanks again...

**Comment by jaor** [comment]
i think this has nothing to do with geiser... looks like something in
your os-x system configuration or racket installation, since it's
happening also with drracket (geiser doesn't touch anything in racket's
installation).  drracket has a configuration option to specify how to
open its help, maybe checking there will give you some hint.

**Comment by ylluminarious** [comment]
@jaor Where specifically is that configuration option in DrRacket? I'd like to try and see if it will make a difference in solving the issue.

**Comment by jaor** [comment]
On Thu, May 18 2017, George D. Plymale II wrote:

> @jaor Where specifically is that configuration option in DrRacket? I'd
> like to try and see if it will make a difference in solving the issue.

at least in linux, under: Edit -> Preferences -> Browser

**Comment by ylluminarious** [comment]
@jaor Thanks for the advice. Unfortunately it seems that option is not there on OS X or under `Preferences -> Browser`. However, as you can see in [this ticket](https://github.com/racket/racket/issues/1685), this issue has been fixed in the pre-release version of Racket so you can mark this issue as closed as far as I'm concerned.

**Comment by jaor** [comment]
thanks a lot for the update, @ylluminarious. closing!
