### ISSUE TITLE
racket geiser server snippet in docs

### ISSUE THREAD

**Issue by 11111000000** [jaor/geiser#239]
There is in docs any simple snippet to inject repl listener?

**Comment by jaor** [comment]
not sure if this is what you're asking for:

  https://github.com/jaor/geiser/blob/master/bin/geiser-racket.sh

(one needs to run make on a configured geiser checkout to get the final
version of that script)

**Comment by 11111000000** [comment]
Yes it is, but how to do it without shell script?

**Comment by jaor** [comment]
sorry, i am not sure i understand what you're trying to accomplish.  you
need to launch a racket process outside emacs, and that example does
just that.  if you're in windows, i guess it's possible to use a
modification of that script as a batch file (sorry, it's been quite a
bit since i used windows and i am not sure of the details).

if what you want is just use geiser without having to launch an external
racket process, all that is needed is `M-x run-racket` inside emacs...

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/geiser/issues/239
