### ISSUE TITLE
maybe a stupid question but ... (repl and load "XXX")

### ISSUE THREAD

**Issue by kinsho6i7h** [jaor/geiser#244]
OK, I'm new to geiser, very new so please excuse me if this is an emacs thing, or a guile thing...

I am reading 'The Little Schemer'

So, I have these 2 files, chapter02.scm and common.scm

atom? is defined in common.scm.

In chapter02.scm, there is a (load "common.scm")

If I open a terminal and start guile, then (load "chapter02.scm"), I get that file, PLUS the loaded definition from 'common.scm'.

In a geiser REPL using guile it's doing something else...

Enter `,help' for help.
scheme@(guile-user)> (define hello 'hello)
scheme@(guile-user)> (atom? hello)
;;; <stdin>:53:0: warning: possibly unbound variable `atom?'
<unnamed port>:53:0: In procedure module-lookup: Unbound variable: atom?

Entering a new prompt.  Type `,bt' for a backtrace or `,q' to continue.
scheme@(guile-user) [1]> (load "common.scm")
scheme@(guile-user) [1]> (atom? hello)
$2 = #t
scheme@(guile-user) [1]> 

The original file is loaded and sent to the repl yet the nested 'common.scm' is not. However, I can then simply load it manually?, define something to test and voila...

So is this normal, common, me or something else as it seems strange.
Thanks
--
Keith

**Comment by jaor** [comment]
geiser does not work well with `load`.  the expected way to load code is
using the module system.  so, in common.scm you would have at the
beginning something like:

      (define-module (tls common)
         #:export (atom? foo bar))

      (define (atom? x) ...)
      (define foo ...)
      (define bar ...)

and then chapter02.scm would start with something like

      (define-module (tls chapter02)
        #:export (...)
        #:use-module (tls common))

      ;; here atom?, foo, bar are visible

If then you open in emacs chapter02.scm, and compile it with `C-c C-k`,
things will hopefully work.  If you want then to go to the REPL in the
(tls chapter02) module, so that all definitions in that file are
visible, you can type, in the buffer that contains chapter02.scm,
`C-u C-c C-z`, and you'll land in the REPL.  You'll see that the prompt
has changed to reflect that you are now in the `(tls chapter02)`
namespace.

althought there are ways to work with guile and geiser without modules,
they are problematic in various ways and using modules is going to be a
much nicer experience once you get used to it.  see also
https://www.gnu.org/software/guile/manual/html_node/Using-Guile-Modules.html

hope this helps!

**Comment by kinsho6i7h** [comment]
Thanks for the heads up, will give that a try and I'm not opposed to modules anyway so no harm.

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/geiser/issues/244
