### ISSUE TITLE
Read from stdin in REPL

### ISSUE THREAD

**Issue by pasja** [jaor/geiser#51]
Today i tried to run the following simple program in geiser, but when i send my buffer with `C-c C-a` to the repl, it hangs. I have to kill racket to get back control over my emacs. I played with `read-line` and i've got no question, but an empty string.

It worked well in drracket and from cli.

```racket
#lang racket

(define test (display (string-append "Hello " (read))))
```
```
racket --version 
Welcome to Racket v6.1.

M-x geiser-version
Geiser 0.7

M-x emacs-version
GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.4.2) of 2015-01-11 on maritornes, modified by Debian
```

Content of the *geiser-messages* buffer
```
WARNING: <25> Droping result for request ",geiser-eval \"/tmp/teszt.rkt\" racket (begin (define myname (read))

(display (string-append \"Hello \" myname))
)": ((error (key . struct:exn:break:terminate)) (output . terminate break

))

WARNING: <2> Droping result for request ",geiser-eval \"/tmp/teszt.rkt\" racket (define test (display (string-append \"Hello \" (read))))": ((error (key . struct:exn:break:terminate)) (output . terminate break

))

WARNING: <3> Droping result for request ",geiser-eval \"/tmp/teszt.rkt\" racket (define test (display (string-append \"Hello \" (read))))": ((error (key . struct:exn:break:terminate)) (output . terminate break

))
```

**Comment by jaor** [comment]
This is expected behaviour.  Evaluation of buffers in Geiser (as
triggered for instance by C-c C-a) sends the code to Racket and expects
a response back with a repl prompt, which in this case never happens
because of the (read).

The equivalent of DrRacket's "Run" or execution via cli can be achieved
in Geiser by evaluation performed *in* the REPL (as opposed to in the
Racket buffer), for instance by requiring the file:

```
racket@> (require (file "/home/jao/tmp/test.rkt"))
"World"
Hello Worldracket@> 
```

Does this answer your question?

**Comment by pasja** [comment]
Thanks for the answer, it worked, but once. If i change the file, and re-require, it does not pick up the changes.

My real question is: which is the preffered geiser way to develop an iteractive Racket cli application, which reads from stdin and outputs to stdout.

Sorry for the noise, i just started the the Racket journey :-)

**Comment by jaor** [comment]
Yep, that's because `require` won't reload the file if it's been already
required.  You could try `,enter <path/to/file>`, but that won't reload
the file unless it's been modified.

What i would suggest is that you encapsulate the actions that read
from the console in functions, and explicitly invoke them in the REPL,
rather than relying on a side-effect of loading the file.  For instance,
instead of

```racket
(define test (display (string-append "Hello " (read))))
```

one could have:

```racket
(define (test) (display (string-append "Hello " (read))))
```

and then, in the REPL, after evaluating the above definition (and
re-evaluating it as many times as you modify it) in the buffer, you just
call the function to test:

```
racket@> (test)
```

**Comment by pasja** [comment]
Thanks for the help!  I think i understand more of the geiser<->racket connection and the difference between a function evaluation and side effect reliance.
