### ISSUE TITLE
Slowness with big list of atoms

### ISSUE THREAD

**Issue by alezost** [jaor/geiser#64]
Hello, I've noticed that Geiser is very slow on returning big lists of
non-lists.  Here is an example.

1. Start Geiser (I used `M-x run-guile`).

2. Define there a couple of auxiliary variables: a big list of
   strings and a big list of lists:

   ```scheme
   (define list-of-strings (make-list 5000 "foo"))
   (define list-of-lists (make-list 5000 '("foo")))
   ```

3. Define an auxiliary elisp function:

   ```elisp
   (defun geiser-simple-eval (str)
     (with-current-buffer (car geiser-repl--repls)
       (let* ((code `(:eval (:scm ,str)))
              (ret (geiser-eval--send/wait code)))
         ;; We don't even need the result, so just return nil.
         ;; (cdr (assq 'result ret))
         nil)))
   ```

4. Now evaluate the following elisp expressions:

   ```elisp
   (geiser-simple-eval "list-of-lists")   ; very fast
   (geiser-simple-eval "list-of-strings") ; very slow
   ```

For me the first expression was evaluated "instantly", while the second
one took about 20 seconds (it depends on CPU of course).

I also checked lists of symbols and lists of numbers: they are also
significantly slower than list of lists.

**Comment by dleslie** [comment]
Which Scheme implementation were you using?

**Comment by alezost** [comment]
guile.  As I wrote I used `M-x run-guile`, but I think it doesn't depend on implementation.

**Comment by dleslie** [comment]
My apologies, I overlooked that.

I will attempt to reproduce with Chicken sometime later today.

**Comment by dleslie** [comment]
Going to spend an hour or two investigating this today.

**Comment by dleslie** [comment]
Just displaying the list of strings in the repl is hideously slow.

**Comment by dleslie** [comment]
Well this is interesting.

I made a small modification to your code:
```elisp

(defun geiser-simple-eval (str)
 (with-current-buffer (car geiser-repl--repls)
   (let* ((code `(:eval (:scm ,str)))
          (ret (geiser-eval--send/wait code 1)))
     ;; We don't even need the result, so just return nil.
     ;; (cdr (assq 'result ret))
     (message "Done")
     )))
```

So it times out after 1 second and displays "Done"

Done is displayed and then Emacs hangs.

**Comment by dleslie** [comment]
So if you display both in the repl the strings one takes a longer time to show. If you disable font-lock-mode this is still the case.

My guess, thus far, is that the temporary buffer that the result is saved to exhibits this same slow down. I'm not certain if there's much that we can do about that, short of checking the length of the result on the scheme side and truncating it.

I'm going to keep digging.

**Comment by dleslie** [comment]
Aha! There's an open issue on this.

http://emacs.stackexchange.com/questions/5545/how-to-prevent-slow-down-when-an-inferior-processes-generates-long-lines

**Comment by dleslie** [comment]
@jaor, I'm not entirely familiar with the connection interface. There doesn't seem to be a clear way to discern when it would be appropriate to truncate responses and when not to. Any thoughts?

**Comment by jaor** [comment]
i'd need to have a closer look, but i think we need the scheme side
generating the result to take care of that.  since the answer comes
through a pipe or a socket in streaming, with a marker at the end, once
it's sent to the emacs side we have little to do.

so it should be the scheme side generating the response that looks at
its length and truncates it, where "truncates" should be some kind of
abbreviation that is still readable as scheme (e.g., the first 20
elements of a list or things like that).

**Comment by dleslie** [comment]
Aye, this may also effect responses from scheme that generate a very long list of completion candidates.

**Comment by dleslie** [comment]
Which would explain why Geiser is a little sluggish with very-short completion prefixes that yield a lot of responses.

For those, maybe a quick fix would be to pretty-print on the scheme side, and so intersperse the response with line breaks?

**Comment by jaor** [comment]
yes, definitely.

**Comment by dleslie** [comment]
#71 appears to fix this issue with Chicken.

This could probably be made to work with Guile using:
https://www.gnu.org/software/guile/manual/html_node/Pretty-Printing.html

And with Racket using:
http://docs.racket-lang.org/reference/pretty-print.html

I'm really short on time this weekend, but I don't mind extending the fix to those if time isn't an issue.

**Comment by jaor** [comment]
i'll take a look at fixing the problem on guile and racket.  thanks a lot dan!

**Comment by jaor** [comment]
hmmm, very curious.  unless i'm doing something silly, trying the same trick with guile has the opposite effect: it doubles execution time (!).  i'll keep digging...

**Comment by jaor** [comment]
oh... i was doing something silly :)

**Comment by jaor** [comment]
pretty printing doesn't help at all in guile.  and the slowdown simply doesn't happen in racket with plain writes.  also, if it was only a matter of long lines, the problem would be still there with `list-of-lists`, but it only happens with `list-of-strings`... paint me perplexed.  i'm marking this bug as guile only and i'll keep digging on its cause.

**Comment by jaor** [comment]
@dleslie @alezost i'm not having much luck with this one.  the patch i submitted making guile use pretty-print helps a little bit, but i'm sure those eols (which are embedded inside a monolithic string) are not the solution.  some guys providing a repl for python mention in the bug report reported by @dleslie that they ended up ditching comint... since every scheme we have behaves in a different manner with regard to this bug, i'm guessing there must be something in the way `write` (or `pretty-print`, which i'm sure uses `write` internally) is implemented (or, more generally, I/O).

**Comment by dleslie** [comment]
Chicken uses Feeley's pretty-print (from 1991!), which doesn't do any internal string-building; and instead it does almost all of its output direct to the provided port. This would be beneficial to Emacs' parser, as it can consume lines as soon as it hits an EOL, rather than receiving a large buffer and then scanning for EOL. It could be that Guile doesn't use this approach.

https://github.com/alaricsp/chicken-scheme/blob/1eb14684c26b7c2250ca9b944c6b671cb62cafbc/extras.scm#L333-L603

**Comment by jaor** [comment]
okay, this one was fun.  big red herring. 

the long delay experienced when evaluating long string lists in Guile
had nothing to do with the time took by emacs to read the response
from the scheme process; that process is always a breeze, no matter or
its format or number of newlines.  The delay was provoked by an
innocent looking function that scans the received string (which
includes a prompt at the end as an EOT marker) to check whether Guile
(or any other scheme) has just entered the debugger (that's done
inside `geiser-con--connection-update-debugging`).  For some reason,
`string-match` on that kind of string using Guile's regexp for a debug
prompt takes forever.  Instead of trying to optimize the regular
expression, i've just applied it to the *second* line of the received
string, which is the one that contains the response's prompt.

i've committed a patch that should have fixed the problem for all
schemes, without the need to use pretty-print (so, if it works and you
feel like that, dan, we could also remove pp in chicken).

would you guys give it a try to check i didn't break anything? thanks!

**Comment by alezost** [comment]
Wow, this is cool!  Now long lists of completions are really fast,
thank you very much!

I have not noticed any breakage so far.

**Comment by dleslie** [comment]
It's a very busy couple of days for me; I won't be able to confirm with my usual alacrity.

**Comment by dleslie** [comment]
In a Chicken buffer, I have issues with eldoc:

```scheme
(define a 1)
(define b '(1 2 3))
(define foo (make-list 10000 "foo"))
a
b
foo
```

```a``` and ```b``` both show eldoc strings properly, but ```foo``` shows nothing.

At some point it started working, with no changes and just time, but then I tried to reproduce that and it seems to be permanently not working.

**Comment by alezost** [comment]
This eldoc issue doesn't seem to present for Guile - everything works as expected.

**Comment by jaor** [comment]
and is this chicken issue something that goes away going back to before
that change?  i don't see any obvious way these changes could influence
autodocs...

**Comment by dleslie** [comment]
I plan to test that later; it's demo day at work, and so I have near-zero free time. ;)

**Comment by dleslie** [comment]
Tested it last night, on the bus ride home. It appears to be a long-standing Chicken issue.

Vote to close; I'll create another issue for Chicken.

**Comment by alezost** [comment]
I've closed it, since the issue is solved, thanks again.
