### ISSUE TITLE
CHICKEN REPL always compiles geiser.scm on boot

### ISSUE THREAD

**Issue by wasamasa** [jaor/geiser#73]
Seems to have been introduced by #68.  Opening the REPL with `C-c C-z` does pause Emacs for a few seconds while `geiser.scm` is compiled as indicated in the debug messages buffer.  Does this need to happen every time?

**Comment by dleslie** [comment]
Yes, this is the case. 

You can disable this behaviour by setting ```geiser-chicken-compile-geiser-p``` to ```nil```, but you may experience other performance issues as a result of running interpreted code.

The reason is that ```compile-file``` isn't clever enough to check for a cached .so and loading the same library on other systems is advised against. There's no strictly simple way to avoid this if we're going to support MELPA-updating of Geiser without an Emacs reload.

**Comment by wasamasa** [comment]
Caching should be relatively simple to do though. Create a file containing the checksum of `geiser.scm` if it doesn't exist yet. If it does exist, compare the checksum of `geiser.scm` with the checksum inside that file. If they don't match up, compile `geiser.scm`.

Or even simpler, if you assume that only MELPA-style updates are done (and people editing the file manually will recompile it, too), they will result in a new directory every time, so just checking for an empty file's existence and creating it if it doesn't exist yet would be enough.

**Comment by dleslie** [comment]
Well, it wasn't quite so simple, but...
