### ISSUE TITLE
0.8 Release and Roadmap

### ISSUE THREAD

**Issue by dleslie** [jaor/geiser#92]
In short: what are the goals for 0.8?

**Comment by jaor** [comment]
if you think chicken support is in good shape, i think we can release
0.8 this week... possibly after investigating issue #60 and issue #61
first...

**Comment by dleslie** [comment]
Just to note, here's the list of commits since 0.7:

https://github.com/jaor/geiser/compare/0.7...master

**Comment by dleslie** [comment]
There are a few Chicken bugs open, but nothing blocking a release.

I guess I have a few questions:
- What about Racket? :wink: I seem to recall you broached the idea of removing support for it. Might I suggest that we add a prompt that alerts Racket users that this is being considered? Something like:
``elisp
(defcustom geiser-saw-racket-warning nil)
(when (and (not geiser-saw-racket-warning) (yes-or-no-p "Warning: Geiser's Racket support is being considered for deprecation. Type 'yes' not to see this warning again."))
  (customize-save-variable geiser-saw-racket-warning t))
```
- It doesn't appear, at first glance, that there are any new 'features'. Is that OK? What features are desirable going forward?

**Comment by jaor** [comment]
sorry for the delay, i've been swamped these last weeks.  in direct conversations with a couple of racketeers, i've got the impression that there's still people using geiser with racket without big problems, so that i guess we can wait a bit more without nagging users.

as of new features, you're right: this could probably be 0.7.1.  in my list of favourite features, it'd be nice to have better debugging interaction (we already have a bit, but there's room for improvement) and perhaps an inspector a la slime.

**Comment by dleslie** [comment]
Wasn't someone working on Gambit support?

**Comment by dleslie** [comment]
Ah, yes, it's mentioned in #56. Pinging @ChrisBlom

**Comment by ChrisBlom** [comment]
Hi, i've stopped working on it for now
